name: Build & Deploy

on:
  push:
    branches: ["main"]
  workflow_run:
    workflows: [Get token data]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: ["20.9.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install packages
        run: npm i

      - name: Run npm build
        run: npm run build

      - name: Copy historical data to dist
        run: cp -r historical dist

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
