name: Get token data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: ["20.9.0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install packages
        run: npm i

      - name: Get data
        run: npm run get-data

      - name: commit to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "automatic commit with token data"
          file_pattern: 'historical/*'
          skip_checkout: true
